name: Deploy Flask to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app

      - name: Deploy to Cloud Run
        env:
          MY_ENV: ${{secrets.MY_ENV}}
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app \
            --platform managed \
            --region southamerica-west1 \
            --allow-unauthenticated \
            --set-build-env-vars=[MY_ENV="${MY_ENV}", LALA=LALA]
            
